apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zq8m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zq8m
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zq8m
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zq8m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zq8m
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dksu-tenant/rhtap-demo-app/hacbs-test-project-zq8m@sha256:ddef64a4048186d6c6c62d3983b3eb750d5933640135a32ff5150399d54f90b3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
